// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using album_collection.Context;

namespace album_collection.Migrations
{
    [DbContext(typeof(AlbumCollectionAPIcontext))]
    [Migration("20200710175441_AddedBand")]
    partial class AddedBand
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("album_collection.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("HomeTown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 55,
                            HomeTown = "Alexandria",
                            ImageName = "image",
                            Name = "The Doors"
                        },
                        new
                        {
                            Id = 2,
                            Age = 58,
                            HomeTown = "New Jersey",
                            ImageName = "image",
                            Name = "Bon Jovi"
                        },
                        new
                        {
                            Id = 3,
                            Age = 39,
                            HomeTown = "Coral Gables",
                            ImageName = "image",
                            Name = "Sonic Youth"
                        },
                        new
                        {
                            Id = 4,
                            Age = 71,
                            HomeTown = "London",
                            ImageName = "image",
                            Name = "Led Zeppelin"
                        },
                        new
                        {
                            Id = 5,
                            Age = 68,
                            HomeTown = "LA",
                            ImageName = "image",
                            Name = "Guns n' Roses"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
