// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using album_collection.Context;

namespace album_collection.Migrations
{
    [DbContext(typeof(AlbumCollectionAPIcontext))]
    [Migration("20200714174851_AlbumSeedData")]
    partial class AlbumSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("album_collection.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Album");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Genre = "Rock",
                            ImageName = "image",
                            Name = "Morrison Hotel",
                            RecordLabel = "Elektra Records",
                            ReleaseYear = 1970
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            Genre = "Rock",
                            ImageName = "image",
                            Name = "Keep the Faith",
                            RecordLabel = "Mercury Records",
                            ReleaseYear = 1992
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 3,
                            Genre = "Rock",
                            ImageName = "image",
                            Name = "Goo",
                            RecordLabel = "GDC Records",
                            ReleaseYear = 1990
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 4,
                            Genre = "Rock",
                            ImageName = "image",
                            Name = "Led Zeppelin IV",
                            RecordLabel = "Atlantic",
                            ReleaseYear = 1972
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 5,
                            Genre = "Rock",
                            ImageName = "image",
                            Name = "Use Your Illusion I",
                            RecordLabel = "Atlantic",
                            ReleaseYear = 1991
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 5,
                            Genre = "Rock",
                            ImageName = "image",
                            Name = "Use Your Illusion II",
                            RecordLabel = "Atlantic",
                            ReleaseYear = 1991
                        });
                });

            modelBuilder.Entity("album_collection.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("HomeTown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 55,
                            HomeTown = "Alexandria",
                            ImageName = "image",
                            Name = "The Doors"
                        },
                        new
                        {
                            Id = 2,
                            Age = 58,
                            HomeTown = "New Jersey",
                            ImageName = "image",
                            Name = "Bon Jovi"
                        },
                        new
                        {
                            Id = 3,
                            Age = 39,
                            HomeTown = "Coral Gables",
                            ImageName = "image",
                            Name = "Sonic Youth"
                        },
                        new
                        {
                            Id = 4,
                            Age = 71,
                            HomeTown = "London",
                            ImageName = "image",
                            Name = "Led Zeppelin"
                        },
                        new
                        {
                            Id = 5,
                            Age = 68,
                            HomeTown = "LA",
                            ImageName = "image",
                            Name = "Guns n' Roses"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Album", b =>
                {
                    b.HasOne("album_collection.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
