// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using album_collection.Context;

namespace album_collection.Migrations
{
    [DbContext(typeof(AlbumCollectionAPIcontext))]
    partial class AlbumCollectionAPIcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("album_collection.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            Genre = "Rock",
                            ImageName = "image",
                            Name = "Morrison Hotel",
                            RecordLabel = "Elektra Records",
                            ReleaseYear = 1970
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            Genre = "Rock",
                            ImageName = "image",
                            Name = "Keep the Faith",
                            RecordLabel = "Mercury Records",
                            ReleaseYear = 1992
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 3,
                            Genre = "Rock",
                            ImageName = "image",
                            Name = "Goo",
                            RecordLabel = "GDC Records",
                            ReleaseYear = 1990
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 4,
                            Genre = "Rock",
                            ImageName = "image",
                            Name = "Led Zeppelin IV",
                            RecordLabel = "Atlantic",
                            ReleaseYear = 1972
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 5,
                            Genre = "Rock",
                            ImageName = "image",
                            Name = "Use Your Illusion I",
                            RecordLabel = "Atlantic",
                            ReleaseYear = 1991
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 5,
                            Genre = "Rock",
                            ImageName = "image",
                            Name = "Use Your Illusion II",
                            RecordLabel = "Atlantic",
                            ReleaseYear = 1991
                        });
                });

            modelBuilder.Entity("album_collection.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("HomeTown")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 55,
                            HomeTown = "Alexandria",
                            ImageName = "image",
                            Name = "The Doors"
                        },
                        new
                        {
                            Id = 2,
                            Age = 58,
                            HomeTown = "New Jersey",
                            ImageName = "image",
                            Name = "Bon Jovi"
                        },
                        new
                        {
                            Id = 3,
                            Age = 39,
                            HomeTown = "Coral Gables",
                            ImageName = "image",
                            Name = "Sonic Youth"
                        },
                        new
                        {
                            Id = 4,
                            Age = 71,
                            HomeTown = "London",
                            ImageName = "image",
                            Name = "Led Zeppelin"
                        },
                        new
                        {
                            Id = 5,
                            Age = 68,
                            HomeTown = "LA",
                            ImageName = "image",
                            Name = "Guns n' Roses"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            Duration = "4:03",
                            Title = "Roadhouse Blues"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 1,
                            Duration = "2:58",
                            Title = "Peace Frog"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 2,
                            Duration = "5:46",
                            Title = "Keep the Faith"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 2,
                            Duration = "6:00",
                            Title = "Bed of Roses"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 3,
                            Duration = "4:06",
                            Title = "Kool Thing"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 3,
                            Duration = "5:30",
                            Title = "Dirty Boots"
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 4,
                            Duration = "5:34",
                            Title = "The Battle Evermore"
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 4,
                            Duration = "7:08",
                            Title = "When the Levy Breaks"
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 5,
                            Duration = "3:02",
                            Title = "Right Next Door to Hell"
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 5,
                            Duration = "4:45",
                            Title = "Don't Cry"
                        },
                        new
                        {
                            Id = 11,
                            AlbumId = 6,
                            Duration = "5:36",
                            Title = "Knockin' on Heaven's Door"
                        },
                        new
                        {
                            Id = 12,
                            AlbumId = 6,
                            Duration = "5:43",
                            Title = "You Could Be Mine"
                        });
                });

            modelBuilder.Entity("album_collection.Models.Album", b =>
                {
                    b.HasOne("album_collection.Models.Artist", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("album_collection.Models.Song", b =>
                {
                    b.HasOne("album_collection.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
